language: node_js
node_js:
  - '0.10'
env:
  global:
  - CODECLIMATE_REPO_TOKEN=102e193d0a54a029ddd90a41753d2176dd6b1451b910c77e36cfb5a4cc5b1510 codeclimate-test-reporter < coverage/**/lcov.info
before_script:
  - npm install -g bower grunt-cli
  - bower install
after_script:
  - codeclimate-test-reporter < coverage/**/lcov.info